@startuml


rectangle Database

actor staff as "Staff Member"

rectangle "World Database" {

 usecase UcPrintPop as "Print population"
 usecase UcPrintCun as "Print countries"
 usecase UcPrintCit as "Print cities"
 usecase UcPrintCapCit as "Print capital cities"
 usecase UcPrintDis as "Print district"
 usecase UcGetN as "Get N"
 usecase UcGetPop as "Get population"
 usecase UcGetCit as "Get city"
 usecase UcGetCapCit as "Get capital cities"
 usecase UcGetDis as "Get district"
 usecase UcGetRegion as "Get Region"
 usecase UcGetCountry as "Get Country"
 usecase UcGetCountries as "Get countries"
 usecase UcGetCont as "Get continent"
 usecase UcPeopleInCit as "Get population of people
                                living in cities"
 usecase UcPeopleOutCit as "Get population of people
                                living out of cities"

/'#1'/
/'As a Staff Member, I want to view all the countries in the world
organised by largest population to smallest.'/

    usecase UC1 as "Get countries
                    by population"

    staff - UC1
    UC1 ..> UcGetCountries : include
    UC1 ..> UcPrintCun : include
    UC1 - Database
/'#2'/
/'As a Staff Member, I want to view all the countries in a continent
organised by largest population to smallest.'/

    usecase UC2 as "Get countries in continent
    by population"

    staff - UC2
    UC2 ..> UcGetCont : include
    UC2 ..> UcPrintCun: include
    UC2 - Database

/'#3'/
/'As a Staff Member, I want to view all the countries in a region
organised by largest population to smallest.'/

    usecase UC3 as "Get countries in region
    by population"

    staff - UC3
    UC3 ..> UcGetRegion : include
    UC3 ..> UcPrintCun : include
    UC3 - Database

/'#4'/
/'As a Staff Member, I want to view the t op N populated countries
in the world where N is provided by the user.'/

    usecase UC4 as "Get top N populated countries"

    staff - UC4
    UC4 ..> UcPrintCun : include
    UC4 ..> UcGetN : include
    UC4 ..> UcGetCountries : include
    UC4 - Database

/'#5'/
/'As a Staff Member, I want to view the t op N populated countries
in a continent where N is provided by the user.'/


    usecase UC5 as "Get top N populated countries
                    in a continent"

    staff - UC5
    UC5 ..> UcPrintCun : include
    UC5 ..> UcGetN : include
    UC5 ..> UcGetCont : include
    UC5 - Database

/'#6'/
/'As a Staff Member, I want to view the t op N populated countries
 in a region where N is provided by the user.'/

    usecase UC6 as "Get top N populated
                    countries in region"

        staff- UC6
        UC6 ..> UcPrintCun : include
        UC6 ..> UcGetRegion : include
        UC6 ..> UcGetN : include
        UC6 - Database

/'#7'/
/'As a Staff Member, I want to view all the cities in the world organised by
largest population to smallest.'/

    usecase UC7 as "Get all cities
    by population"

    staff - UC7
    UC7 ..> UcGetCit : include
    UC7 ..> UcPrintCit : include
    Database - UC7

/'#8'/
/'As a Staff Member, I want to all view the cities in a continent organised by largest population to smallest.'/

    usecase UC8 as "Get all cities in continent
    by population"

    staff - UC8
    UC8 ..> UcGetCont : include
    UC8 ..> UcPrintCit : include
    Database - UC8


/'#9'/
/'As a Staff Member, I want to view the cities an a region organised by population descending.'/

    usecase UC9 as "Get all cities an a region
     by population"

    staff - UC9
    UC9 ..> UcPrintCit : include
    UC9 ..> UcGetRegion : include
    UC9 -- Database


/'#10'/
/'As a Staff Member, I want to view cities in a country by population.'/

    usecase UC10 as "Get cities in country
    by population"

    staff - UC10
    UC10 ..> UcPrintCit : include
    UC10 ..> UcGetCountry : include
    Database - UC10


/'#11'/
/'As a Staff Member, I want to view cities in a District by population.'/

    usecase UC11 as "Get cities in District
    by population"

    staff - UC11
    UC11 ..> UcPrintCit : include
    UC11 ..> UcGetDis : include
    Database - UC11

/'#12'/
/'As a Staff Member, I want to view the top N populated cities in the world
where N is provided by the user.'/

    usecase UC12 as "Get top 'N' populated
                    cities in the world"

    staff - UC12
    UC12 ..> UcGetN: include
    UC12 ..> UcGetCit : include
    UC12 ..> UcPrintCit: include
    UC12 - Database


/'#13'/
/'As a Staff Member, I want to view the top N populated cities in a continent where N is provided by the user.'/

    usecase UC13 as "Get the top N populated
                    cities in a continent"

    staff - UC13
    UC13 ..> UcGetCont : include
    UC13 ..> UcGetN : include
    UC13 ..> UcPrintCit : include
    Database - UC13

/'#14'/
/'As a staff member I want to view the to N populated cities in a region where N is provided by user'/

    usecase UC14 as "View top N populated cities in a region"

    staff - UC14
    UC14 ..> UcGetN : include
    UC14 ..> UcGetRegion : include
    UC14 ..> UcPrintCit : include
    UC14 - Database

/'#15'/
/'As a Staff Member, I want to view the top N populated cities in country where N is provided by the user.'/


    usecase UC15 as "Get top 'N' populated
                    cities in a county"

    staff - UC15
    UC15 ..> UcGetN : include
    UC15 ..> UcGetCit : include
    UC15 ..> UcPrintCit : include
    UC15 - Database

/'#16'/
/'As a Staff Member, I want to view the top N populated cities in a district
 where N is provided by the user.'/

    usecase UC16 as "Get the top N populated cities
                      in a district"

    staff - UC16
    UC16 ..> UcGetN : include
    UC16 ..> UcGetDis : include
    UC16 ..> UcPrintCit : include
    UC16 - Database

/'#17'/
/'As a Staff Member, I want to view all capital cities in the world
organised largest population to smallest.'/

    usecase UC17 as "Get all capital cities in
                     the world by population"

    staff - UC17
    UC17 ..> UcGetCapCit : include
    UC17 ..> UcPrintCapCit : include
    UC17 - Database

/'#18'/
/'As a Staff Member, I want to view all capital cities in a continent organised largest population to smallest.'/

    usecase UC18 as "Get all capital cities in
                     continent by population"

    staff - UC18
    UC18 ..> UcGetCont : include
    UC18 ..> UcPrintCapCit : include
    UC18 - Database

/'#19'/
/'As a Staff Member, I want to view all capital cities in a region organised largest population to smallest.'/

    usecase UC19 as "Get all capital cities in a
                     region by population"

    staff - UC19
    UC19 ..> UcGetRegion : include
    UC19 ..> UcPrintCapCit : include
    UC19 - Database

/'#20'/
/'As a Staff Member, I want to view the top n populated capital cities in the world.'/

    usecase UC20 as "Get top 'N' populated
                    capital cities"

    staff - UC20
    UC20 ..> UcGetN : include
    UC20 ..> UcGetCapCit: include
    UC20 ..> UcPrintCapCit : include
    UC20 - Database

/'#21'/
/'As a Staff Member, I want to view the top n populated capital cities in a continent.'/

    usecase UC21 as "Get top 'N' populated
                    capital cities in a continent"

    staff - UC21
    UC21 ..> UcGetN : include
    UC21 ..> UcGetCont : include
    UC21 ..> UcPrintCapCit : include
    UC21 - Database

/'#22'/
/'As a Staff Member, I want to view the top n populated capital cities in a region.'/

    usecase UC22 as "Get top 'N' populated
                    capital cities in a region"

    staff - UC22
    UC22 ..> UcGetN: include
    UC22 ..> UcGetRegion : include
    UC22 ..> UcPrintCapCit
    UC22 - Database

/'#23'/
/'As a staff member I want to view the population of people living in cities and not living in cities in each continent'/

    usecase UC23 as "Get population of people
                     living in and out of cities
                     in each continent"

    staff - UC23
    UC23 ..> UcGetCont : include
    UC23 ..> UcPeopleInCit : include
    UC23 ..> UcPeopleOutCit : include
    UC23 ..> UcPrintPop : include
    UC23 - Database


/'#24'/
/'As a staff member I want to view the population of people living in cities and not living in cities in each region'/

    usecase UC24 as "Get population of people
                     living in and out cities in
                     each region"

    staff - UC24
    UC24 ..> UcGetRegion : include
    UC24 ..> UcPeopleInCit : include
    UC24 ..> UcPeopleOutCit : include
    UC24 ..> UcPrintPop : include
    UC24 - Database

'#25'/
/'As a staff member I want to view the population of people living in cities and not living in cities in each country'/

    usecase UC25 as "Get population of people
                     living in and out of cities"

    staff - UC25
    UC25 ..> UcGetCountry : include
    UC25 ..> UcPeopleInCit : include
    UC25 ..> UcPeopleOutCit : include
    UC25 ..> UcPrintPop : include
    UC25 - Database


/'#26'/
/'As a Staff Member, I want to view the population of the world.'/

    usecase UC26 as "Get the population of the world"

    staff - UC26
    UC26 ..> UcGetPop : include
    UC26 ..> UcPrintPop : include
    Database - UC26

'#27'/
/'As a staff member I want to view the population of a continent'/

    usecase UC27 as "Get population of a continent"

    staff - UC27
    UC27 ..> UcGetCont : include
    UC27 ..> UcPrintPop : include
    UC27 - Database

/'#28'/
/'As a staff member I want to view the population of a region'/

    usecase UC28 as "Get population of a region"

    staff - UC28
    UC28 ..> UcGetRegion : include
    UC28 ..> UcPrintPop : include
    UC28 - Database

/'#29'/
/'As a staff member I want to view the population of country'/

    usecase UC29 as "Get population of a country"

    staff - UC29
    UC29 ..> UcGetCountry : include
    UC29 ..> UcPrintPop : include
    Database - UC29

 /'#30'/
 /'As a Staff member I want to view the population of a district.'/

    usecase UC30 as "Get population of a district"

    staff - UC30
    UC30 ..> UcPrintDis : include
    UC30 ..> UcGetDis : include
    Database - UC30

/'#31'/
/'As a Staff Member, I want to view the population of a city.'/

    usecase UC31 as "Get the population of a city"

    staff - UC31
    UC31 ..> UcPrintPop : include
    UC31 ..> UcGetCit : include
    Database - UC31


/'#32'/
/'As a Staff Member, I want to view the number of people who speak a language, from greatest number to smallest (Including percentage)'/

    usecase UC32 as "Get the number of people who
    speak a language by number of speakers as a
    including percentage"

    usecase UC32a as "Print language and
                      number of speakers"

    usecase UC32b as "Print Percentage of
                      all fluent speakers"

    staff - UC32
    UC32 ..> UC32a : include
    UC32 ..> UC32b : include
    Database - UC32
}
left to right direction
@enduml