@startuml

/'#12'/
/'As a Staff Member, I want to view the top N populated cities in the world where N is provided by the user.'/

    usecase UC12 as "Get top 'N' populated
                    cities in the world"

    usecase UCa12 as "Get user input for 'N'"

    usecase UCb12 as "Print cities"

    SM12 - UC12
    UC12 ..> UCa12: include
    UC12 ..> UCb12: include
    UC12 - Database12
}

/'#12'/
/'As a Staff Member, I want to view the top N populated cities in country where N is provided by the user.'/


    usecase UC15 as "Get top 'N' populated
                    cities in a county"

    staff - UC15
    UC15 ..> UcGetN : include
    UC15 ..> UcPrintCit : include
    UC15 - Database
}

/'#17'/
/'As a Staff Member, I want to view al capital cities in the world organised largest population to smallest.'/

    usecase UC17 as "Get all capital cities in
                     the world by population"

    staff - UC17
    UC17 ..> UcGetN : include
    UC17 ..> UcPrintCit : include
    UC17 - Database
}

/'#18'/
/'As a Staff Member, I want to view all capital cities in a continent organised largest population to smallest.'/

    usecase UC18 as "Get all capital cities in
                     continent by population"


    staff - UC18
    UC18 ..> UcGetCont : include
    UC18 ..> UcGetCapCit : include
    UC18 ..> UcPrintCit : include
    UC18 - Database
}

/'#19'/
/'As a Staff Member, I want to view all capital cities in a region organised largest population to smallest.'/

    usecase UC19 as "Get all capital cities in a
                     region by population"

    staff - UC19
    UC19 ..> UcGetRegion : include
    UC19 ..> UcGetCapCit : include
    UC19 ..> UcPrintCit : include
    UC19 - Database
}

/'#20'/
/'As a Staff Member, I want to view the top n populated capital cities in the world.'/

    usecase UC20 as "Get top 'N' populated
                    capital cities"

    SM20 - UC20
    UC20 ..> UcGetN : include
    UC20 ..> UcGetCapCit: include
    UC20 ..> UcPrintCit
    UC20 - Database20
}

/'#21'/
/'As a Staff Member, I want to view the top n populated capital cities in a continent.'/

    usecase UC21 as "Get top 'N' populated
                    capital cities in a continent"

    SM21 - UC21
    UC21 ..> UcGetN : include
    UC21 ..> UcGetCont : include
    UC21 ..> UcPintCapCit : include
    UC21 - Database21
}


/'#22'/
/'As a Staff Member, I want to view the top n populated capital cities in a region.'/

    usecase UC22 as "Get top 'N' populated
                    capital cities in a region"

    staff - UC22
    UC22 ..> UcGetN: include
    UC22 ..> UcGetRegion : include
    UC22 ..> UcPrintCapCit
    UC22 - Database

left to right direction
@enduml